### ISSUE TITLE
JS error in Safari.

### ISSUE THREAD

**Issue by scopeak** [proteusthemes/themeforest-preview-bar#5]
Hey guys,

Switcher is great, however I am receiving a JS error with Safari. Can't be replicated with Chrome.

```
TypeError: btn.addEventListener is not a function. (In 'btn.addEventListener('click', toggleViewport)', 'btn.addEventListener' is undefined)
(anonymous function)main.js:206
forEach
initmain.js:205
readymain.js:12
(anonymous function)main.js:211
(anonymous function)main.js:310
```

This also appears on refresh.

```
TypeError: undefined is not an object (evaluating '$el.search.length')
decoratemain.js:253
(anonymous function)main.js:305
forEach
decoratorHandlermain.js:304
```

Cheers!

**Comment by primozcigler** [comment]
Hi there @scopeak 

Thank you!

Hmmm, which version of Safari is this? It might be very old as `addEventListener` is supported in modern browser for couple of years now.

**Comment by scopeak** [comment]
Hey, the latest on El Capitan. 9.0.3

**Comment by primozcigler** [comment]
My coworker @Prelc confirmed this problem. I will investigate in the next days.

**Comment by primozcigler** [comment]
@scopeak I changed something in JS. Can you please pull the code and check again?

**Comment by primozcigler** [comment]
@Prelc confirmed this issue is gone now. I am closing the issue. Please reopen if the problem persists. And thank you for reporting.

**Comment by scopeak** [comment]
All good now! No problem, glad to help.
